version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - Dandandan
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: libc
    versions:
    - 0.2.84
    - 0.2.85
    - 0.2.86
    - 0.2.87
    - 0.2.88
    - 0.2.89
    - 0.2.90
    - 0.2.91
    - 0.2.92
    - 0.2.93
  - dependency-name: wasm-bindgen
    versions:
    - 0.2.70
    - 0.2.71
    - 0.2.72
  - dependency-name: regex
    versions:
    - 1.4.3
    - 1.4.4
    - 1.4.5
  - dependency-name: regex-syntax
    versions:
    - 0.6.22
  - dependency-name: quote
    versions:
    - 1.0.8
  - dependency-name: proc-macro2
    versions:
    - 1.0.24
  - dependency-name: version_check
    versions:
    - 0.9.2
